var genre = ["action","adventure","comedic","crime","non fictional", "fantastical","historical","horror",
"mysterious","paranoia","philosophical", "romantic","satirical","science fiction","slice of life",
"speculative","thriller","heros journey","western","super hero origin story", "punk as fuck",
"Shakespearean","parody","romantic comedy","zombie", "courtroom drama","detective story","whodunnit",
"murder mystery", "fairy tale","dying earth rescue","post-apocalypse","alternate history of WWI",
"alternate history of WWII","biographical","ghost story","hack and slash", "utopic","distopic","survivalist",
"paranormal romance","erotic","suspense driven", "cyberpunk","space opera","space western","steampunk","slipstream",
"supernatural","Tron-esque","time-travel", "science-fiction","dramatic reenactment",
"romance driven", "travel guide", "self help", "children\'s", "religious",
"mathmatical", "historically accurate", "anthology", "poetic", "comedic",
"art focused", "painterly", "fantasy", "trilogy", "absurdist", "surreal",
"whimsical", "crime drama", "magical realism", "paranoid fiction", "saga",
"slice of life", "urban drama", "live action", "hero\'s journey", "military fiction",
"spy fiction", "girls with guns", "superhero", "tall tale", "black comedy",
"courtroom drama", "detective story", "hardboiled", "legal thriller", "docudrama",
"melodrama", "teen romance", "contemporary fantasy", "fable", "fairy tale",
"epic fantasy", "mythic fiction", "memoir", "counterfactual history", "period piece",
"ghost story", "giant monster", "slasher", "survival comedy", "tech noir",
"space opera", "cyberpunk", "retropunk", "dieselpunk", "biopunk", "distopian", "utopian",
"psychological thriller", "techno thriller", "traditionally animated", "sitcom",
"game show", "instructional", "sport-based", "soap opera"];
var type = ["RTS","RPG","MMORPG","retro beat em up","shooter", "stategy game","turn based strategy",
"simulation game","puzzle platformer", "party game","platformer","fighter","racing game","civilization game",
"pet simulator game","survival horror","sport game","stealth game","musical game", "shoot em up","pinball game",
"MOBA","rail shooter","tactical shooter", "point and click adventure game","mascot fighting game",
"visual novel", "western RPG","eastern RPG","artillery game","MMORTS","MUD","tower defense", "wargame",
"indie game","rogue","rogue like","rogue like like","rogue like like like","rogue light","metroidvania","sandbox game",
"trivia game","advergame","art game", "educational game","casual game","religious game","serious game", "vintage run and gun",
"MMOFPS", "MMORTS", "VR experience", "installation", "paper based role playing game", "LARP", "turn based strategy game",
"tower defense", "music puzzle game", "ongoing open world game", "party game", "lawn game", "outdoor game",
"depressing platformer", "table top game", "visual novel", "platforming survival game", "one hit one kill game",
"real time 3D adventure", "tactical LARP", "interactive movie", "unchangable choice game", "management game",
"real time adventure game", "sandbox game", "AR location based game", "vehicle simulation", "text adventure", "Amazon Alexa game",
"vector game", "DOOM clone", "non-linear game", "city building game", "a lost world game", "physics puzzle-platformer",
"government simulation game", "serious game","ecological simulation game","god game",
"pet-raising simulation", "flight simulator", "4X game", "MR experience", "escape the room game", "dating simulation"];
var about = ["unicorns", "random acts of kindness", "dreams","the frail plight of humanity against the vastness of space",
"trying to clean up before your boss comes back","that feeling of uneasiness at seeing someone you used to be friends with",
"trying to find your cat","the strange things that hide under your bed","wondering if it's worth it to get out of bed for a drink of water",
"the fall of a kingdom only you can save","Harry Potter and his magical adventures","trying to write your first novel",
"two people who can never never lays eyes on each other else they explode","the human conciousness",
"waking up to realize you are a dog","just two guys who are having a good time", "the cold realization that you're are an adult",
"walking home in the rain","trying to get a stone out of your shoe","waking up to an empty bed","trying to write a web app",
"biking too fast while being drunk","going on a roadtrip to unknown destinations","buying your first car",
"trying to save the Prince of Whales","going tabogoning","trying to escape a locked room","going on a walk in the forest",
"exploring the ocean floor","starting your first apiary","learning to fly as a baby bird",
"making your way downtorn","trying to get back into your mother's pouch as a baby kangaroo","trying to find your zombified body as a ghost",
"the first time you hang out with someone","trying to solve your best friends murder","figuring out what you should do that weekend",
"trying to catch them all","giving fashion advice to people who cannot dress themselves","inventing reality television shows",
"plotting the demise of western society","spuring the uprising of the people of Atlantis","finding out how SLURM is made",
"trying to describe an 8th colour","memorizing the hex colour system", "the endless loop of time","making bacon in your underwear",
"finding a rift in the space time continuum","messing with physics","trying to get through a first date",
"living life in the 1st dimension","how mitochondria is the powerhouse of the cell","falling in love",
"falling out of love","taking down the patriarchy","eating a squished Joe Luois","a bubblegum goth",
"studying for an exam you had yesterday","trying to become famous on the internet","making a sandwich",
"making a sea witch","making a sand witch","making an air witch","becoming the singularity","awakening the dark beast",
"making tribute to the Volcano God","trying to take your child to school across a busy highway","having too much inner peace",
"having too many inner peas","trying to escape the hoard of terrible bees","waking up 3 hours late for work","bees",
"shooting rainbows out of your butt","trying to cope with living in the 21st century","a time traveller from Scotland who goes about in a police box",
"being the first person to live on Mars","trying to get custody of your child","trying to barter with God",
"waiting in line at the DMV","having to walk all the way there because the buses stopped running",
"trying to convince your mother of your life choices","the optimism of childhood","the frustration of mansplaining",
"learning falconry","trying to build a treehouse","trying to build a greenhouse","the brief terror of waking up from a dream without knowing where you are yet",
"walking through a Dali painting","getting a tattoo for the first time","the frustation of the elderly","the frustration of watching young children trying to complete complex tasks",
"experiencing snow for the first time","trying to start a circus","bee circuses","trying to figure out what to wear in the morning",
"trying to genetically engineer pokemon","manually transcribing an almanac","getting way to high and having to leave a party",
"sifting through OkCupid messages","trying not to fall asleep in class","trying to make it as an artist",
"trying to escape the faculities","short multiplication problems","learning a new language","trying to escape the underworld",
"inking your first comic book","meeting your favourite author and not knowing what to say","writing JQuery",
"trying to render JavaScript before the document has loaded","buying yourself groceries","having to call your mother",
"explaining what happened in the accident","ordering pizza in sign language","writing so many string statement you don't even know what it is you are doing anymore",
"designing a logo for a friend and never getting paid","working on group projects","trying to give your cat a flea bath",
"taking a bath at the end of a long day","replacing one word with another","the frustration of a broken elevator",
"Facebook removing their birthday feature and having to remember everyone's birthday manually again",
"learning to knit for the first time","the difference between opening a present at 5 and 55",
"two roads diverged in a yellow wood","wearing high heels to the club in the middle of a snow storm",
"how Facebook chat has replaced passing notes in class","trying to make a group project work",
"taking a plane by yourself for the first time","the feeling of watching animals in a zoo",
"the realization that you've used perminant marker on a white board","being still alive",
"designing a card game","getting trapped in a glacier","going to a BBQ as a vegetarian",
"travelling back in time to realize that the world was just as cold and empty as it is now",
"taking advantage of a small amount of free time to take a nap","wanting to pet your cat but they really do not want to be held",
"trying to destroy everything in an exs house before they come back","the encroaching void","an unceasingly dry lecturer",
"academic intergrity","your dog eating your taxidermy","taking a class in a subject you have no experience in",
"falling in and out of friendship over the years","laying next to a warm body","laying next to a cold body",
"being in love with someone you can never tell","never knowing someone loved you until years too late",
"watching ants and wondering if there is a god","going to four beaches in a day","debating what reality is and isn\'t",
"loosing your depth perception","how the more you travel the harder it is to settle down","using augmentation to better your life",
"regretting the cybernetic augmentations of the future","counting your steps to deal with your stress",
"realizing the futility of frustration","singing on a mountain top","watching a sunset alone",
"singing in the shower","being introduced to someone you already know by a mutual friend","getting bewitched in the woods",
"reaching out","learning to use your non dominant hand","trying to make a billion dollar idea",
"going for a walk in the middle of the night because you can\'t' sleep","being given shoes by a friend",
"cooking dinner for someone who is sick","getting sick the moment after you finish something important",
"getting sick right before doing something important","the hollowness of going to a resort for a vacation",
"the feeling of the hair raising on the back of your neck","using the cloud to offset your processing on site",
"working minimum wage with a masters degree","working minimum wage with an undergraduate degree",
"working minimum wage with a PHD","wanting to climb someone like a tree","climbing a tree to escape wild dogs",
"making friends with wild animals","the anxiety of going to a place where you do not know anyone","technology that no one uses",
"floating on your back in the Dead Sea","making friends with an otter","doing mathmatics as a pass time",
"the relieving feeling of understanding your place in an ecosystem","being so stressed you simply lay on the floor",
"walking barefoot in the city","catching your own food","sleeping under the stars","realizing sleeping under the stars was a terrible idea because of all of the bugs",
"the smell of a campfire","eating freshly caught game meat","watching a sports game you have no idea what the rules are",
"going to a bar","going to a gay bar","cracking your joints in an effort to relieve the never ending pressure of age",
"the cold that seeps into your bones during the winter that never goes away","rolling down a hill and realizing there are a lot of stones",
"scanning a QR code and having porn pop up instead of anything useful","actually using a QR code",
"the joy of eating your favourite food","watching a horror movie with someone you like","touching your toes",
"taking pictures of people in class without them knowing","never using snapchat for your genitals",
"using the TTC","trying to use something that no one did UI testing for","getting more information from someone than you intended",
"creating a TROJAN horse virus","meeting an old friend for tea","getting really good at cooking one meal",
"living on the couch of someone you just met the night before","getting punched in the face at a punk show",
"stick and poke tattoos","drinking underage by a bridge","playing chicken on an empty highway",
"sailing from island to island","being a pirate","driving all night and never seeing another car",
"visiting road side stops to break up the monotony","smoking to stay awake","Burning Man","sleeping in a hammock",
"touchyourtoes.com","knowing the bartender at your favourite bar","getting beat up in an alleyway",
"having the talk with your parents","the morbid fascination with seeing roadkill","knowing things would never work out",
"wanting everything to be okay","trying to understand the GitHubb application without terminal","stealing your parents food",
"watching bad movies with your roommate","venting so much you can't breath","pulling your hamstring",
"watching YouTube while eating to feel less alone","learning a new skill just because you can",
"drunkenly setting your hair on fire","fall asleep drunk in a snowbank","drinking alone in a pub",
"crashing a wedding","staying friends with someone you met on a plane","giving money to the homeless",
"having to clean out your fridge","your GPS taking you to somewhere you never entered","living in your car",
"visiting another country where you know no one","curling into the fetal position","making ceramics",
"gardening","building your own house","eating more take out than home cooked food","playing the games you can remember from childhood",
"how hoarse your voice gets when you stop talking to everyone who annoys you","how obsessed everyone is with butts, including you",
"that awkward moment when a speaker says something offensive and asks everyone to agree with them",
"dehydrating apples","snuggling up to a warm fire with a boozy drink","learning burlesque",
"buying the cheapest meat at the butcher","nostalgia glasses","drawing comics about the strange adventures of your friends",
"playing video games until dawn","drunkenly watching sunrise and knowing you won't see it again for a while",
"spray painting an underpass","running away from the cops","sleeping in a red wood tree","crossing the border",
"shovelling the snow","putting too much salt in your soup","envying other people skills","going to a protest and getting gased",
"aspiring to climb Mt. Everest until you see the line up","driving through a tree","holding a baby lion and the confliction of the emotional weight of it",
"the pull of the void","walking on the edge of a cliff, knowing you could end your life at anytime, and the terror of that power",
"feeling the magnetic fields in the world", "the frustration of different programming languages","your princess being in Snother castle",
"an app not being available for your device","fighting a battle you know you cannot win","shapeshifting enemies",
"asking for help and getting more confused","making lunch the night before","code jamming with your friends",
"trying to reach word count on an essay","trying to get down to word count on an essay","colour coding your work",
"using way too many particle effects","classes that teach you things you already know","trying not to be noticed while oogling someone",
"meowing at your cat and having them meow back","wrapping yourself in so many blankets because you don't have heating in your house",
"constantly getting vertigo","getting celebrities mixed up in conversation","forgetting peoples names",
"picking your own fruit","going camping for the first time and having everything go wrong","learning survival skills",
"using google images to find where the first instance of a picture is","drinking a bottle of wine to yourself",
"a labyrinth","a maze","sketching out your ideas before making stuff","trying to sell a broken product",
"making snow angels","seeing someone you think you know","making a playdate for your kid","installing a new driver",
"the over reaching hand of the state","making texts from the predictive suggestions from your phone",
"breaking out of your comfort bubble","just being silly for silliness sake","trying to figure out modern art",
"the normalization of abusive behavior over time","telling a story more than once to refine it","kittens",
"hallway conversations at a party","wanting to leave before all of your friends at a party","how the singularity is inevitable",
"the frustration of watching a movie adaptation of your favourite novel","feeding ducks bread","symbiotic relationships between creatures",
"oversharing","learning about the flow of electricity","watching your ideas take form","how colour affects the mood of a person",
"the multiverse","the emotional weight of knowing something you can never share","finding a mentor in the field you want to know more about",
"the flexibility and fragility of friendship","the weird greetings between old friends","sitting in comfortable silence",
"the week where your entire life falls appart","the suble nature of smiling","cultural differences",
"a cautionary tale about strangers","trying a new food","finding a hiding space all your own as a child",
"the trust built between a team of people who work constantly together","a goblin horde","the dispelling of misunderstandings",
"approaching a stranger for directions","gossiping about others","how information degrades and changed between tellings",
"the mysteries of the unknown","the unsetting sun of the north","finding someone so attractive you can't think of anything to say",
"taking too much time to get somewhere","arriving way to early for something for fear of being late","superstitions",
"touching your face to know that everything is okay","deja vu","3D scanning a donkey","taking the scenic route",
"trying to understand quantum physics","waiting for an order that will never arrive","waiting anxiously for your mail order bride",
"setting up an account for a service that you'll never use","flipping the table while playing Monopoly",
"hording sheep for brick","complex political relations","the sad ex girlfriend beer","paddling a canoe in circles",
"involving the Demon Lord David","the Lemmithon","fighting a blue dragon","encountering a small wooden shack",
"fighting with magic for the first time","sitting waiting for the bus","sitting on your ass trying to figure out what to do with your life",
"almost dipping your fries in beer instead of condements","waiting for an eye appointment","getting on the next plane",
"running a marathon","skating on a frozen lake","travelling faster than the speed of light","buying a couch",
"making an appointment","building a table","getting a new pet","trying to do a presentation without saying like",
"putting eyedrops in","having a fight with a police officer","getting to a business right as it closes",
"winding down after a long day at work","trying to explain something in a new language","singing to yourself instead of listening to music",
"having a migraine","fighting in an underground boxing ring","meeting your professor for beers","carrying a knife to feel safe walking home",
"wearing the same pair of jeans longer than you should","playing grounders in a playground as an adult","finding the monsters under your bed",
"walking home at night","trying to stay warm when your house is barely above freezing","having to go to the bathroom during a presentation",
"contacting your MP","the Canadian accent","falling through the ice","taking your dog for a walk around the block",
"running into an old friend and realizing you have nothing in common anymore","planting your own food","tomato or tamato",
"going on a date for the last time","driving away","going on a drive without destination because you don't know what else to do",
"guessing if characters are CGI or puppets in movies","pupil dilation","the anxiety of hearing your friends laughing in another room",
"forgetting your line on opening night","fighting the sinking feeling telling you not to leave the house",
"the inevitable robot uprising","slowly loosing your sight","climbing on the art","jumping out of a window into a giant snowbank",
"making a band with your friends","getting into a car with someone you just met","praying","taking up the mantle",
"carrying the Olympic Torch","your dog barking at an empty hallway","building your own house","getting lost in Canadian Tire",
"not checking the weather forecast before leaving the house","muscle memory","getting somewhere late but before the person you're meeting",
"forgoing your security deposit","punching a hole in the wall","getting lost at sea", "a runaway dog", "a former lover",
"a city of roses", "a lonely stranger", "a creature made of mist","the concept of the universe itself", "a swamp thing",
"the unknowable","a werewolf", "a siren", "the moment in which you first knew yourself", "realizing the vasteness of the universe",
"a formless mass", "getting a masters because you're scared of being a real adult", "being a REAL adult", "emotional labour", "a science witch",
"the creeping sense of embarassment that you were wrong and have been arguing a bad point for the past fourty-five minutes",
"a wandering storyteller", "telling secrets", "finding secrets", "hiding secrets", "a friendly fiddler", "a metal cover band", "piloting your corpse mech",
"the person who has basically the same schedule as you and you always see them on your cigarette break", "a trash panda", "a cobra chicken", 
"the ever encroaching hand of capitalism", "punching nazis", "forgiving yourself", "a literal dumpster fire",
"a ska band touring the east coast", "getting trapped in an ice storm", "the first time you knew yourself", " a gentle touch from a stranger",
"a literal train", "toxic masculinity", "transitioning", "a thousand dogs howling in unison", "the darkness just beyond the bend in the woods",
"going deeper and deeper into the void", "a single showlace", "that drawer you have all the bobbles in", "lasers pew pew", "derailing a conversayion",
"avoiding a hard conversation with your partner", "passive aggressive social media posts", "the taste of blood in your mouth", "navigating your mental health",
"forgiving your body for being flawed", "exploring an abandoned parking garage", "escaping your students after a particularily controversial lecture",
"a bear in the woods", "not one but several chicken", "an inexscapable labyrinth", "cooking your friends their favourite meal", "organizing your bookshelf",
"an old man offering you a sword", "a siren singing songs to lure men to their deaths", "using sheeps knuckles as dice",
"literal garbage", "the epic quest of a caterpiller to a butterfly", "the reaching hand of Satan", "exploring the world as a toddler", "associating images with words to build language",
"a cursed sewing machine", "making clothing", "a fight to the death", "the Internet of Things", "an AI that really just wants you to leave it alone",
"the demons in the corners of your vision", "trying to escape a counter counting down to an explosion", "attempting to swallow a river", "a vial filled with unknown blood",
"summoning a demon to be your friend", "getting out of a bad friendship", "human teeth", "making candles", "trapping the last breath of the dying in a jar",
"childhood memories", "six sewing needles and a bottle of gin", "going sober", "relapse", "a warm cup of tea", "the ocean", "wanding into the dark void of the sea",
"following train tracks", "a lock of human hair", "climbing a glacier", "picking flowers",
"taking photographs", "exploring city parks", "your personal hero", "muchroom picking", "sewing your lips shut", "laying down and waiting until death consumes you", "making a broom", "a thousand crows decending upon a town",
"a yellow leaf", "trying not to be caught falling asleep in a meeting", "a handful of herbs given to you by a passing grandmother", "communing with the dead",
"you cat staring into nothingness then running away from the dark", "a couple of stones", "being choked", "throwing out the box of things your ex left behind and didn't want back",
"a literal mountain", "a weaving river", "a burbling brook", "a sack of runes given to you by Odin himself", "an old pack of cigarettes",
"the needles you got your first tattoo with in a silk bag", "an alter under the bridge", "foraging food", "a seagull that follows you", "a panda",
"an artificial heart beating with yours", "a blanket fort", "the insistent ticking of the clock", "a salamander", "a fishhook", "a hand me down stained-glass lamp",
"a snake skin", "recieving a package in the mail from an unknown sender", "gathering vials of tears", "conserving heat on the long cold walk home",
"a selkie", "rock climbing", "finding the perfect stone", "Baba Yaga", "taking care of plants", "taking care of business", "bird song", "a forest of birdcage",
"sacrificing a loved one to the Old Gods", "trying to prevent your own death", "trying to get an Amazon package for free", "eating a bagel",
"breaking and resetting bones", "visiting gravestones", "meeting a stranger at a bar", "controlling the tides", "break everything", "pulling your own teeth",
"cooking soup", "making candles", "fighting with your dog trying to get them to swallow a pill", "picking edible flowers", "discovering an ancient grove","picking up the stones to overthrow your government",
"collecting dirt from everywhere you go", "trying to swim from one island to the next", "recapturing that 1990s feeling of the internet", "repainting a living room", "calming your anxiety",
"sorting through mementos", "describing memories", "skinning a hide", "going to the bar alone", "releasing anger", "letting go", "waiting until the grave is filled after the funeral has ended",
"warm clothing", "riding transit to the end of the line", "drinking in the park with your friends", "finding a place to sleep when you have nowhere to go", "giving away your last cigarette",
"running away", "finding a new place to be", "arson matches", "whittling", "ink blotches", "being stuck in a small space", "cutting your own hair", "dropping bouncy balls", 
"making friends", "making promises", "breaking promises", "keeping promises", "your relationship with your mother", "your relationship with your father", "your relationship with your sibling/s", 
"your relationship with your best friend", "your relationship with your parter", "lashings", "tying knots", "holding on", "butt plugs", "fucking someone you really, really shouldn\'t", "stealing", "doing crimes", 
"release", "itching", "loosing", "winning", "catorgarizing", "making a farm", "taking care of yourself", "a death debt", "sea salt",
"gouging out your eyes", "trying to be the last one to hang up on a phone call", "MSN", "forgetting", "sailing", "watching your whole world fall apart",
"the soft touch of a gentle stranger", "the nightmares", "the demons that live down on 7th street", "blood rituals", "a house that makes music when it rains",
"blood and cotton", "being trapped inside a small space", "being possessed", "finding a date", "a bookstore", "a coffeeshop", "the coffeeshop from FRIENDS", "a coffee pirate ship",
"international trade", "supply chains", "reinventing the wheel", "making streetart", "splitting the rainbow", "finding an 8th colour", "inking a drawing", 
"cracking a stone heart", "breaking windows", "sprouting plants", "seedbombs", "subway hammocks", "birds that live on the river", "the Queen\'s swans", "the stories handed down through the streets", "the stories handed down through the trees",
"the Son of the Tree That Owned Itself", "sewing buttons into someone\'s eyes", "reality as an ever changing  narrative", "drinking a sunset", "the city of unfinished thoughts and half remembered dreams", "finsind the perfect aftershave",
"it not working out", "not leaving your house for as long as possible", "wild berries", "being a literal bear", "trying to befriend a cat", "ferrets burrowing complex tunnels", "bringing home a new baby", 
"your engine dying while driving through rural Ohio", "cross stitching", "trying to make people leave through white noise", "busting anti homeless city infastructure", 
"falling in love with yourself", "accidentally super liking your friend on Tindr", "leaving before your one night stand can wake up",
"brewing beer", "sitting in the trunk of a car", "roadtripping with your friends", "gentrification", "the heat death of the universe","waking up early to get to a meeting",
"going to a concert", "living it up", "only have 2 dollars to you name", "winning the lottery", "pulling lion teeth", "the encircling hyenas", "making camp for the night",
"cutting down trees", "exploring the ocean", "exploring the forest", "exploring the city", "navigating with a map to a different place","collecting memories",
"finding a better life", "farts", "making dinner with your friends", "making dinner for a date", "steamed hams", "impressing your boss", "navigating with a bag GPS", 
"digital naturalism", "taking care of a zoo", "reaching out", "getting outdoors", "hitchhiking", "hiking", "getting what you\'re owed", "stab wounds","vertigo","walking barefoot through fire",
"a volcano God", "an exploding volcano", "buying a used car", "finding work after undergrad", "getting a degree in neuroscience", "getting a degree", "dropping out of high school",
"catching butterflies", "hiding from the light", "hiding from the dark", "making small talk with a stranger at the bus stop", "carving yourself from clay", "stealing gas", "the fall of the United States",
"writing a constitution", "climbing trees", "hiding as many knives on your body as you can", "sneaking things through the TSA", "tasting wine", "a never-ending winter", "a never-ending summer","making a difference",
"going to an island", "tracking down your killer", "being a ghost", "catching ghosts", "making sick beats", "catching an elk", "fixing the sewer system", "ecology", "crafting your own ecosystem",
"being a vampire", "being a werewolf", "falling in love with a monster", "dating a construct", "different art movements", "Kusama", "running from the cops", "stealing construction equiptment","falling asleep",
"the afterlife", "a mediated conversation", "mediating a conversation", "sitting down and talking it out", "throwing bottles at oncoming trains", "moving cities", "taking pictures of normal people as if they were celebrities",
"getting to know someone", "finally giving into entropy", "entropy", "making potions", "body horror", "demons created out of your greatest fears", "match-making", "BEES",
"making a golem in your own image", "seeing the sun for the first time in a long time", "a long line of cars", "chopping trees", "sitting down and finally writing it all out", "all the weird things that happened at your first apartment",
"a house fire", "a tree falling down", "keeping chickens in the city", "listening to a lover\'s breathing", "realizing you never loved them at all", "an amicable break up", "a messy break up", "picking at scars",
"healing scars", "being an inch worm", "finally giving into your animalistic nature", "breathing in and out", "taking the time to reply to that email you've been avoiding", "generations of peasents", "being a shopkeeper in a medieval town",
"keeping adventures out of your castle", "waiting outside for your friend to sneak out", "moving back with your parents", "the futility of time", "running out of time", "running into time", "the end of the universe", "the number 42",  
"game making", "matching cards", "playing fiddle with the devil", "playing cards with your friends", "being alone for the first time", "your earliest childhood memory", "a DND campaign",
"catching frogs", "fishing", "a failing farm on the outskirts of the city", "trying to keep your house from being rezoned by the city", "rezoning a city", "building an intentional community",
"the tiniest house possible", "sleeping in your car", "giving in to your depepest fear", "entirely formless terror", "embracing the void","getting into a fancy party you weren\'t invited to",
"envy", "wanting to do better by someone", "cliff jumping", "giving up on the city and moving to a small town", "trying to get as far north as possible", "the suburbs", "tree roots", "digging your own grave",
"time travel", "a city made entirely of bones", "a necropolis","a cobbler", "a hat maker", "a mad hatter", "a butcher", "a candlestick maker", "stealing a car worth many times over what you are",
"community gardening", "saving a baby bird", "raising a city", "not being able to touch anything", "that feeling you get when you finally realize that you're a tiny speck in the universe",
"gravity no longer working", "shooting bubblegum", "hiding your gum after you're done with it but being too lazy to find a trash can", "giving up a bad habit","changing liceanse plates", "nail marks on the door after you close it",
"rereading Shakespeare as an adult", "hunting without any tools but your ability to run for a really, REALLY long time","moving to a different country", "writing song in your car", "the place where you feel safest",
"ruining a friendship", "singing while walking", "listening to the ocean breath","becoming a barista", "taking a job on you don't know how to do",
"climbing a mountain", "digging a tunnel through a mountain", "driving across the country", "hiking the Appalachian trail", "figuring out your own indigeneity", "stealing from the Hudson Bay","a house party where you know everyone",
"a house party where you know no one","finding a hidden waterfall", "climbing a waterfall", "stitching together a band of rebels into a flurishing anarchist society","complete anarchy","gloves","a speculative world where everyone repsects each other",
"your own utopia", "your personal distopia", "a distopic tale of a wandering salesman", "having octopus hands", "drift wood", "redwood trees big enough you can live in them", "tiny bugs",
"taking care of succulents", "growing a human in a vat", "an ariary", "an aquarium", "a terrarium", "a vivarium", "interstellar space travel", "battling mechs made out of your love",
"robots coexisting with humans", "the last human alive", "the fall of society", "birch trees", "bonsai", "poetry", "driving a milk truck", "rebuilding the house your great grandparents bought, lived, and died in",
"spiders", "making friends as a conference", "going to GDC", "eating alone in a crowded restaurant", "getting a private room", "making friends on the floor", "laying down and observing the stars with your friends",
"stargazing", "getting out of the car on the side of the road to have an arguement", "the forbidden love between a bird and a fish", "creating a system of governence never seen before", "piles of meat", "the shambling corpse of a deer speaking in your mother\'s voice",
"a tuna salad sandwich", "a blue fin tuna", "travelling the world", "the loneliness of not making any connections at a meet up", "share holders", "starting a company", "creating a media monopoly", "YouTube", "going to court", "being a lawyer",
"archery", "going to the Pride parade", "naming plant mutations", "CRISPR", "being an Uber driver", "being the bouncer at a club", "having knife hands",
"the unknowably huge universe", "dating the planets", "finding your soulmate and getting it wrong", "a ribbon tied around your girlfriend\'s kneck she refuses to take off", "alchemy",
"the meaning of life", "the last fight you had", "renting a camper van and going out into the woods with nothing but a hatchet and your dog", "trying not to adopt all the dogs in the shelter", "finding shelter", "a crotchety badger named Ralph",
"following graffiti to a secret location", "a VR experience within a video game in which they're playing a character having a VR experience", "VR porn",
"an Alexa chanting angrily", "shaving your beard", "telling your partner you're queer", "forgiving", "ripping your enemies heart out", "being the most authentic you possible",
"waking up as a zebra", "waking up with flippers for hands", "braiding hair", "being a tattoo artist with picky clientele", "vigilanty justice",
"snap back hats", "living life as if it were a Sufjan Stevens song", "being gay for God", "telecommunicating with the old gods", "working in a call centre", "confessing your love to your best friend", "trying to pet an angry cat",
"snuggling up to a warm fire with a cup of tea and telling stories", "transforming into a giant panda", "full moonlight on cold wet skin", "reading books in the library",
"kicking ass and taking names", "relocating a shoulder", "trying to find a mythic shoe", "using someone elses computer and everything being just slightly wrong", "having a day off","the Dewey Decimal system",
"the breath of the ocean", "the lingering scent of rotten blood from a slaughter house", "taking action against the government", "how you found your best friend","stubbing your toe", "having a leg cramp in a meeting and trying to hide it from your boss",
"red rover", "sitting in a playground at night wondering where all your childhood memories went", "finding the centre of everything", "using your olfactory sense to navigate the world", "an eighth colour", "becoming omnipotent", "having a television for a head that broadcasts your every through to those around you",
"inhabiting the form of a fawn by day", "finding the best truth you can from an archive", "tracking a bear", "the origins of fire","going north",
"D R A G O N S", "playing a DND campaign and trying to navigate the super personal stuff people put into their characters", "the colour orange", "legal boxes filled with papers about you",
"being a first time parent", "discovering new species", "building a log cabin in the woods", "navigating walking as if you were a sailboat", "being a pirate", "being alright", "leaving your home town and never looking back",
"being a pickpocket", "white gold", "a kind gentleman", "being tied to the ocean side", "packing a suitcase as effeciently as possible", "getting a dog", "sweeping that existential dread under the rug",
"stealing the launch codes to finally end nuclear armsment", "building a house right across from you ex husband out of spite", "meeting up with an old friend and it feeling as if no time has passed at all", "meeting up with an old friend and it feeling as if you never knew them at all",
"rebuilding after the fire", "a street brawl", "tijme travel but only to the most awkward moments in lived existance", "digging your own grave", "your twilight years", "going to the hairdresser", "acting out all the fears your parents worried about",
"stealing a penguin from a zoo", "your personal hero", "robot legs", "Icarus falling in love with the sun", "realizing at 25 that this is just it", "feeling invinsible at 19", "graduating and having no idea how to apply yourself", "applying yourself",
"volunteering", "a distance thunderstowm rumbing on the horizon", "building IKEA furniture with someone you don't know", "something you know absolutely nothing about and probably should", "woodworking", 
"the soft reading voice of a parent lulling their child to sleep", "Macbeth", "A cauldron", "a suit too big for the funeral", "giving yourself a stick and poke tattoo",
"every dog on the planet barking in unison and acending to a higher conciousness", "dog actually being the source of the internet", "tinfoil hat theories", "the sound of an old modem screaming",
"the universe opening up as a giant eye and screaming at your in tongues on a chilly Tuesday afternoon", "a thousand eyes blinking in unison", "gracing the public with your presence","being seen by someone you\'re avoiding",
"getting sucker punched", "sucker punching your enemies", "being a shop keeper defending your shop from adventurers looking to steal from you", "being light as a feather and stiff as a cyborg", "navigating the medical system",
"passing out on your friend\'s couch", "getting a foot massage", "listening to someone leave a messege on an old answering machine", "building the best rig you can", "fixing an old car", "uploading yourself to the cloud",
"defending yourself", "an old girlfriend passing you on the street", "becoming a forest", "building a treehouse", "building your own house", "buying a plot of land and starting a farm", "berry picking",
"joining a vigilanty group", "watching the watchmen", "fermenting food", "trying to plant food plants without the city figuring it out", "fishing", "forgetting everything you once knew",
"the encroaching failure of your human form", "quitting smoking", "making installations", "your artistic style and how you found it","an underwater labratory abandoned for unknown reasons"
"puking out an old god", "creating a blood pact", "visiting your parents", "attending a friend\'s funeral", "writing a book", "identifying different buttons from a line up", "making your first game",
"loosing yourself during a trip", "trudging down the mountain", "your mother being a literal washing mashine", "resting your head on the cold ground"];

document.getElementById("genre").innerHTML=genre[Math.floor(Math.random() * genre.length)];
document.getElementById("type").innerHTML=type[Math.floor(Math.random() * type.length)];
document.getElementById("about").innerHTML=about[Math.floor(Math.random() * about.length)];