var genre = ["action","adventure","comedic","crime","non fictional", "fantastical","historical","horror",
"mysterious","paranoia","philosophical", "romantic","satirical","science fiction","slice of life",
"speculative","thriller","heros journey","western","super hero origin story", "punk as fuck",
"Shakespearean","parody","romantic comedy","zombie", "courtroom drama","detective story","whodunnit",
"murder mystery", "fairy tale","dying earth rescue","post-apocalypse","alternate history of WWI",
"alternate history of WWII","biographical","ghost story","hack and slash", "utopic","distopic","survivalist",
"paranormal romance","erotic","suspense driven", "cyberpunk","space opera","space western","steampunk","slipstream",
"supernatural","Tron-esque","time-travel" ];
var type = ["RTS","RPG","MMORPG","retro beat em up","shooter", "stategy game","turn based strategy",
"simulation game","puzzle platformer", "party game","platformer","fighter","racing game","civilization game",
"pet simulator game","survival horror","sport game","stealth game","musical game", "shoot em up","pinball game",
"MOBA","rail shooter","tactical shooter", "point and click adventure game","mascot fighting game",
"visual novel", "western RPG","eastern RPG","artillery game","MMORTS","MUD","tower defense", "wargame",
"indie game","rogue","rogue like","rogue like like","rogue like like like","rogue light","metroidvania","sandbox game",
"trivia game","advergame","art game", "educational game","casual game","religious game","serious game"];
var about = ["unicorns", "random acts of kindness", "dreams","the frail plight of humanity against the vastness of space",
"trying to clean up before your boss comes back","that feeling of uneasiness at seeing someone you used to be friends with",
"trying to find your cat","the strange things that hide under your bed","wondering if it's worth it to get out of bed for a drink of water",
"the fall of a kingdom only you can save","Harry Potter and his magical adventures","trying to write your first novel",
"two people who can never never lays eyes on each other else they explode","the human conciousness",
"waking up to realize you are a dog","just two guys who are having a good time", "the cold realization that you're are an adult",
"walking home in the rain","trying to get a stone out of your shoe","waking up to an empty bed","trying to write a web app",
"biking too fast while being drunk","going on a roadtrip to unknown destinations","buying your first car",
"trying to save the Prince of Whales","going tabogoning","trying to escape a locked room","going on a walk in the forest",
"exploring the ocean floor","starting your first apiary","learning to fly as a baby bird",
"making your way downtorn","trying to get back into your mother's pouch as a baby kangaroo","trying to find your zombified body as a ghost",
"the first time you hang out with someone","trying to solve your best friends murder","figuring out what you should do that weekend",
"trying to catch them all","giving fashion advice to people who cannot dress themselves","inventing reality television shows",
"plotting the demise of western society","spuring the uprising of the people of Atlantis","finding out how SLURM is made",
"trying to describe an 8th colour","memorizing the hex colour system", "the endless loop of time","making bacon in your underwear",
"finding a rift in the space time continuum","messing with physics","trying to get through a first date",
"living life in the 1st dimension","how mitochondria is the powerhouse of the cell","falling in love",
"falling out of love","taking down the patriarchy","eating a squished Joe Luois","a bubblegum goth",
"studying for an exam you had yesterday","trying to become famous on the internet","making a sandwich",
"making a sea witch","making a sand witch","making an air witch","becoming the singularity","awakening the dark beast",
"making tribute to the Volcano God","trying to take your child to school across a busy highway","having too much inner peace",
"having too many inner peas","trying to escape the hoard of terrible bees","waking up 3 hours late for work","bees",
"shooting rainbows out of your butt","trying to cope with living in the 21st century","a time traveller from Scotland who goes about in a police box",
"being the first person to live on Mars","trying to get custody of your child","trying to barter with God",
"waiting in line at the DMV","having to walk all the way there because the buses stopped running",
"trying to convince your mother of your life choices","the optimism of childhood","the frustration of mansplaining",
"learning falconry","trying to build a treehouse","trying to build a greenhouse","the breif terror of waking up from a dream without knowing where you are yet",
"walking through a Dali painting","getting a tattoo for the first time","the frustation of the elderly","the frustration of watching young children trying to complete complex tasks",
"experiencing snow for the first time","trying to start a circus","bee circuses","trying to figure out what to wear in the morning",
"trying to genetically engineer pokemon","manually transcribing an almanac","getting way to high and having to leave a party",
"sifting through OkCupid messages","trying not to fall asleep in class","trying to make it as an artist",
"trying to escape the faculities","short multiplication problems","learning a new language","trying to escape the underworld",
"inking your first comic book","meeting your favourite author and not knowing what to say","writing JQuery",
"trying to render JavaScript before the document has loaded","buying yourself groceries","having to call your mother",
"explaining what happened in the accident","ordering pizza in sign language","writing so many string statement you don't even know what it is you are doing anymore",
"designing a logo for a friend and never getting paid","working on group projects","trying to give your cat a flea bath",
"taking a bath at the end of a long day","replacing one word with another","the frustration of a broken elevator",
"Facebook removing their birthday feature and having to remember everyone's birthday manually again",
"learning to knit for the first time","the difference between opening a present at 5 and 55",
"two roads diverged in a yellow wood","wearing high heels to the club in the middle of a snow storm",
"how Facebook chat has replaced passing notes in class","trying to make a group project work",
"taking a plane by yourself for the first time","the feeling of watching animals in a zoo",
"the realization that you've used perminant marker on a white board","being still alive",
"designing a card game","getting trapped in a glacier","going to a BBQ as a vegetarian",
"travelling back in time to realize that the world was just as cold and empty as it is now",
"taking advantage of a small amount of free time to take a nap","wanting to pet your cat but they really do not want to be held",
"trying to destroy everything in an exs house before they come back","the encroaching void","an unceasingly dry lecturer",
"academic intergrity","your dog eating your taxidermy","taking a class in a subject you have no experience in",
"falling in and out of friendship over the years","laying next to a warm body","laying next to a cold body",
"being in love with someone you can never tell","never knowing someone loved you until years too late",
"watching ants and wondering if there is a god","going to four beaches in a day","debating what reality is and isnt",
"loosing your depth perception","how the more you travel the harder it is to settle down","using augmentation to better your life",
"regretting the cybernetic augmentations of the future","counting your steps to deal with your stress",
"realizing the futility of frustration","singing on a mountain top","watching a sunset alone",
"singing in the shower","being introduced to someone you already know by a mutual friend","getting bewitched in the woods",
"reaching out","learning to use your non dominant hand","trying to make a billion dollar idea",
"going for a walk in the middle of the night because you cannot sleep","being given shoes by a friend",
"cooking dinner for someone who is sick","getting sick the moment after you finish something important",
"getting sick right before doing something important","the hollowness of going to a resort for a vacation",
"the feeling of the hair raising on the back of your neck","using the cloud to offset your processing on site",
"working minimum wage with a masters degree","working minimum wage with an undergraduate degree",
"working minimum wage with a PHD","wanting to climb someone like a tree","climbing a tree to escape wild dogs",
"making friends with wild animals","the anxiety of going to a place where you do not know anyone","technology that no one uses",
"floating on your back in the Dead Sea","making friends with an otter","doing mathmatics as a pass time",
"the relieving feeling of understanding your place in an ecosystem","being so stressed you simply lay on the floor",
"walking barefoot in the city","catching your own food","sleeping under the stars","realizing sleeping under the stars was a terrible idea because of all of the bugs",
"the smell of a campfire","eating freshly caught game meat","watching a sports game you have no idea what the rules are",
"going to a bar","going to a gay bar","cracking your joints in an effort to relieve the never ending pressure of age",
"the cold that seeps into your bones during the winter that never goes away","rolling down a hill and realizing there are a lot of stones",
"scanning a QR code and having porn pop up instead of anything useful","actually using a QR code",
"the joy of eating your favourite food","watching a horror movie with someone you like","touching your toes",
"taking pictures of people in class without them knowing","never using snapchat for your genitals",
"using the TTC","trying to use something that no one did UI testing for","getting more information from someone than you intended",
"creating a TROJAN horse virus","meeting an old friend for tea","getting really good at cooking one meal",
"living on the couch of someone you just met the night before","getting punched in the face at a punk show",
"stick and poke tattoos","drinking underage by a bridge","playing chicken on an empty highway",
"sailing from island to island","being a pirate","driving all night and never seeing another car",
"visiting road side stops to break up the monotony","smoking to stay awake","Burning Man","sleeping in a hammock",
"touchyourtoes.com","knowing the bartender at your favourite bar","getting beat up in an alleyway",
"having the talk with your parents","the morbid fascination with seeing roadkill","knowing things would never work out",
"wanting everything to be okay","trying to understand the GitHubb application without terminal","stealing your parents food",
"watching bad movies with your roommate","venting so much you can't breath","pulling your hamstring",
"watching YouTube while eating to feel less alone","learning a new skill just because you can",
"drunkenly setting your hair on fire","fall asleep drunk in a snowbank","drinking alone in a pub",
"crashing a wedding","staying friends with someone you met on a plane","giving money to the homeless",
"having to clean out your fridge","your GPS taking you to somewhere you never entered","living in your car",
"visiting another country where you know no one","curling into the fetal position","making ceramics",
"gardening","building your own house","eating more take out than home cooked food","playing the games you can remember from childhood",
"how hoarse your voice gets when you stop talking to everyone who annoys you","how obsessed everyone is with butts, including you",
"that awkward moment when a speaker says something offensive and asks everyone to agree with them",
"dehydrating apples","snuggling up to a warm fire with a boozy drink","learning burlesque",
"buying the cheapest meat at the butcher","nostalgia glasses","drawing comics about the strange adventures of your friends",
"playing video games until dawn","drunkenly watching sunrise and knowing you won't see it again for a while",
"spray painting an underpass","running away from the cops","sleeping in a red wood tree","crossing the border",
"shovelling the snow","putting too much salt in your soup","envying other people skills","going to a protest and getting gased",
"aspiring to climb Mt. Everest until you see the line up","driving through a tree","holding a baby lion and the confliction of the emotional weight of it",
"the pull of the void","walking on the edge of a cliff, knowing you could end your life at anytime, and the terror of that power",
"feeling the magnetic fields in the world", "the frustration of different programming languages","your princess being in Snother castle",
"an app not being available for your device","fighting a battle you know you cannot win","shapeshifting enemies",
"asking for help and getting more confused","making lunch the night before","code jamming with your friends",
"trying to reach word count on an essay","trying to get down to word count on an essay","colour coding your work",
"using way too many particle effects","classes that teach you things you already know","trying not to be noticed while oogling someone",
"meowing at your cat and having them meow back","wrapping yourself in so many blankets because you don't have heating in your house",
"constantly getting vertigo","getting celebrities mixed up in conversation","forgetting peoples names",
"picking your own fruit","going camping for the first time and having everything go wrong","learning survival skills",
"using google images to find where the first instance of a picture is","drinking a bottle of wine to yourself",
"a labyrinth","a maze","sketching out your ideas before making stuff","trying to sell a broken product",
"making snow angels","seeing someone you think you know","making a playdate for your kid","installing a new driver",
"the over reaching hand of the state","making texts from the predictive suggestions from your phone",
"breaking out of your comfort bubble","just being silly for silliness sake","trying to figure out modern art",
"the normalization of abusive behavior over time","telling a story more than once to refine it","kittens",
"hallway conversations at a party","wanting to leave before all of your friends at a party","how the singularity is inevitable",
"the frustration of watching a movie adaptation of your favourite novel","feeding ducks bread","symbiotic relationships between creatures",
"oversharing","learning about the flow of electricity","watching your ideas take form","how colour affects the mood of a person",
"the multiverse","the emotional weight of knowing something you can never share","finding a mentor in the field you want to know more about",
"the flexibility and fragility of friendship","the weird greetings between old friends","sitting in comfortable silence",
"the week where your entire life falls appart","the suble nature of smiling","cultural differences",
"a cautionary tale about strangers","trying a new food","finding a hiding space all your own as a child",
"the trust built between a team of people who work constantly together","a goblin horde","the dispelling of misunderstandings",
"approaching a stranger for directions","gossiping about others","how information degrades and changed between tellings",
"the mysteries of the unknown","the unsetting sun of the north","finding someone so attractive you can't think of anything to say",
"taking too much time to get somewhere","arriving way to early for something for fear of being late","superstitions",
"touching your face to know that everything is okay","deja vu","3D scanning a donkey","taking the scenic route",
"trying to understand quantum physics","waiting for an order that will never arrive","waiting anxiously for your mail order bride",
"setting up an account for a service that you'll never use","flipping the table while playing Monopoly",
"hording sheep for brick","complex political relations","the sad ex girlfriend beer","paddling a canoe in circles",
"involving the Demon Lord David","the Lemmithon","fighting a blue dragon","encountering a small wooden shack",
"fighting with magic for the first time","sitting waiting for the bus","sitting on your ass trying to figure out what to do with your life",
"almost dipping your fries in beer instead of condements","waiting for an eye appointment","getting on the next plane",
"running a marathon","skating on a frozen lake","travelling faster than the speed of light","buying a couch",
"making an appointment","building a table","getting a new pet","trying to do a presentation without saying like",
"putting eyedrops in","having a fight with a police officer","getting to a business right as it closes",
"winding down after a long day at work","trying to explain something in a new language","singing to yourself instead of listening to music",
"having a migraine","fighting in an underground boxing ring","meeting your professor for beers","carrying a knife to feel safe walking home",
"wearing the same pair of jeans longer than you should","playing grounders in a playground as an adult","finding the monsters under your bed",
"walking home at night","trying to stay warm when your house is barely above freezing","having to go to the bathroom during a presentation",
"contacting your MP","the Canadian accent","falling through the ice","taking your dog for a walk around the block",
"running into an old friend and realizing you have nothing in common anymore","planting your own food","tomato or tamato",
"going on a date for the last time","driving away","going on a drive without destination because you don't know what else to do",
"guessing if characters are CGI or puppets in movies","pupil dilation","the anxiety of hearing your friends laughing in another room",
"forgetting your line on opening night","fighting the sinking feeling telling you not to leave the house",
"the inevitable robot uprising","slowly loosing your sight","climbing on the art","jumping out of a window into a giant snowbank",
"making a band with your friends","getting into a car with someone you just met","praying","taking up the mantle",
"carrying the Olympic Torch","your dog barking at an empty hallway","building your own house","getting lost in Canadian Tire",
"not checking the weather forecast before leaving the house","muscle memory","getting somewhere late but before the person you're meeting",
"forgoing your security deposit","punching a hole in the wall","getting lost at sea"];